# config/run_config.yaml

# General settings
city_lore_file: "data/city_lore.txt"   # Static city background
openai_model: "gpt-4o-mini"            # Model to use for all agents
temperature: 0.7                       # Creativity level
max_tokens: 200                        # Output length cap

# Test environment
use_mock_data: false                  # For test runs
mock_data_file: "tests/fixtures/sample_story.json" # For test runs

# Which agents to run
agents:
  story_teller: true
  stat_estimator: true
  name_creator: true
  item_creator: false          # optional
  tales_teller: false          # optional
  family_history: false        # optional

story_teller:
  openai_model: "gpt-4o-mini"
  temperature: 0.7
  max_tokens: 200

name_creator:
  openai_model: "gpt-4o-mini"
  temperature: 0.7
  max_tokens: 200

# Output settings
save_outputs: true
output_format: "json"          # or markdown
output_folder: "outputs/"

# D&D-specific constraints
stat_range:
  min: 6
  max: 18
